import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Navbar: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Ndsddr component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        vsfdsdf
    </div>
  )
}

export default Navbar
